//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace AtlasAI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid AgentActionAI = new Guid("4b109d495b3204ba391d483dfe5844c3");
		public static readonly Guid AgentMoveAI = new Guid("0eba4c6f1f7cc4e6f9ebab9daa403469");
		public static readonly Guid AgentScanAI = new Guid("0471a1f77889e4f93ab116ffb68292c4");

    }
}
